# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/sova0413/happyroom"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/yYzEJ4Qe"

[ejs.settings]
sourceGithubLink = "https://github.com/sova0413/happyroom"
supportLink = "https://github.com/sova0413/happyroom/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO Happyroom"
welcomeDescription = "해피룸에 오신 것을 환영합니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
