# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/sova0413/happyroom"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://aztra.xyz/invite/pC6XSDJQ"

[ejs.settings]
sourceGithubLink = "https://github.com/sova0413/happyroom"
supportLink = "https://github.com/sova0413/happyroom/issues"

[ejs.welcome]
welcomeHeader = "오션서버에 오신 것을 환영합니다!"
welcomeDescription = "반야생, RPG 오션서버입니다."
welcomeDescCTA = "몇번의 클릭만 더 하시면 됩니다!"
